AWSTemplateFormatVersion: 2010-09-09
Description: EKS cluster for EKS sample

Parameters:
  Project:
    Description: Project name
    Type: String
  EKSRoleArn:
    Description: Arn of the role that EKS will assume
    Type: String
  ControlPlaneSecurityGroup:
    Description: ID of the securitygroup for EKS cluster
    Type: String
  PrivateSubnets:
    Description: List of subnets where nodes are deployed
    Type: String
  PublicSubnets:
    Description: List of Subnets where alb is deployed
    Type: String

Resources:
  EKS:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub ${Project}-cluster
      Version: 1.11
      RoleArn: !Ref EKSRoleArn
      ResourcesVpcConfig:
        SecurityGroupIds:
        - !Ref ControlPlaneSecurityGroup
        SubnetIds:
          !Split [',', !Join [',', [!Ref PrivateSubnets, !Ref PublicSubnets]] ]

Outputs:
  ClusterName:
    Description: Name of the EKS cluster
    Value: !Ref EKS
    Export:
      Name: !Sub ${AWS::StackName}:ClusterName