AWSTemplateFormatVersion: "2010-09-09"

Description: |
  This stack creates a SNS topic using KMS encryption and a CloudWatch alarm to monitor the SNS topic.

Parameters:
  KmsKey:
    Description: The KMS key master ID
    Type: String

Resources:

  # A SNS topic
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: !Ref KmsKey

  # CloudWatch alarm for the SNS topic
  TopicAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm for SNS topic metrics"
      MetricName: NumberOfMessagesPublished
      Namespace: AWS/SNS
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: TopicName
          Value: !Ref Topic
      AlarmActions:
        - "arn:aws:sns:REGION:ACCOUNT_ID:YOUR_SNS_TOPIC_FOR_ALARMS"