AWSTemplateFormatVersion: '2010-09-09'

Resources:
  SecurityAdminsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SecurityAdmins
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com, lambda.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSReadOnlyAccess
      Policies:
        - PolicyName: SecurityAdminsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - fis:*
                  - iam:CreateServiceLinkedRole
                  - iam:PassRole
                Resource: '*'

  AdminsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Admins
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com, lambda.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSReadOnlyAccess
      Policies:
        - PolicyName: AdminsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - fis:*
                  - iam:CreateServiceLinkedRole
                  - iam:PassRole
                Resource: '*'
              - Effect: Deny
                Action:
                  - fis:*
                Resource:
                  - '*'
                Condition:
                  StringEquals:
                    aws:ResourceTag/Environment: 'prod'

  UsersRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Users
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com, lambda.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSReadOnlyAccess
      Policies:
        - PolicyName: UsersPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - fis:StartExperiment
                  - fis:StopExperiment
                  - fis:Get*
                  - fis:List*
                  - fis:TagResource
                  - fis:UntagResource
                Resource: '*'
              - Effect: Deny
                Action:
                  - fis:*
                Resource:
                  - '*'
                Condition:
                  StringEquals:
                    aws:ResourceTag/Environment: 'prod'

  NonUsersRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: NonUsers
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com, lambda.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSReadOnlyAccess
      Policies:
        - PolicyName: NonUsersPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Deny
                Action:
                  - fis:*
                Resource: '*'