AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Cluster with Fargate Support

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties: {}

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
    DependsOn: ECSCluster

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
    DependsOn:
      - ECSCluster
      - TaskDefinition

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Fargate Configuration
        Parameters:
          - Cpu
          - Memory
          - DesiredCount
    ParameterLabels:
      Cpu:
        default: CPU Units
      Memory:
        default: Memory (MB)
      DesiredCount:
        default: Number of Tasks