AWSTemplateFormatVersion: '2010-09-09'

Description: "Template for creating S3 Bucket for CUR Files and CUR Reports - AWS::CUR::ReportDefinition works only in us-east-1 (2021-07-14)"

Parameters:

  ReportName:

    Type: String

    Default: "CUR-AthenaReport"

    Description: Name of the report.

  GlueDatabaseName:

    Type: String

    Default: "cur_report"

    Description: Name of the report - only lower case letters.

  S3Prefix:

    Type: String

    Default: "cur"

    Description: prefix used for report

Resources:

  # S3 Bucket

  S3Bucket:

    Type: AWS::S3::Bucket

    Properties:

      BucketName: !Sub mycur-bucket-${AWS::AccountId}

      PublicAccessBlockConfiguration:

        BlockPublicAcls: true

        BlockPublicPolicy: true

        IgnorePublicAcls: true

        RestrictPublicBuckets: true

  #BucketPolicy for CUR

  BucketPolicy:

    Type: AWS::S3::BucketPolicy

    Properties:

      Bucket: !Ref S3Bucket

      PolicyDocument:

        Id: CURPolicy

        Version: '2008-10-17'

        Statement:

          - Sid: GetSecuritySettings

            Action:

              - s3:GetBucketAcl

              - s3:GetBucketPolicy

            Effect: Allow

            Resource: !Sub "arn:aws:s3:::${S3Bucket}"

            Principal:

              Service: "billingreports.amazonaws.com"

          - Sid: PutCURFiles

            Action:

              - s3:PutObject

            Effect: Allow

            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"

            Principal:

              Service: "billingreports.amazonaws.com"

  #CUR

  CostAndUsageReport:

    Type: AWS::CUR::ReportDefinition

    Properties:

      AdditionalArtifacts:

        - ATHENA

      AdditionalSchemaElements:

        - RESOURCES

      Compression: Parquet

      Format: Parquet

      RefreshClosedReports: true

      ReportName: !Ref ReportName

      ReportVersioning: OVERWRITE_REPORT

      S3Bucket: !Ref S3Bucket

      S3Prefix: !Ref S3Prefix

      S3Region: !Sub ${AWS::Region}

      TimeUnit: HOURLY

  # Athena workgroup

  AthenaWorkGroup:

    Type: AWS::Athena::WorkGroup

    Properties:

      Name: CURWorkGroup

      Description: WorkGroup for CUR operations

      State: ENABLED

      WorkGroupConfiguration:

        BytesScannedCutoffPerQuery: 5000000000

        EnforceWorkGroupConfiguration: false

        PublishCloudWatchMetricsEnabled: false

        RequesterPaysEnabled: true

        ResultConfiguration:

          OutputLocation: !Sub 's3://${S3Bucket}/${S3Prefix}/${ReportName}/athena-workgroup-output/'

  #Athena and Glue - based on AWS Template https://docs.aws.amazon.com/cur/latest/userguide/use-athena-cf.html

  AWSCURDatabase:

    Type: 'AWS::Glue::Database'

    Properties:

      DatabaseInput:

        Name: !Ref GlueDatabaseName

      CatalogId: !Ref AWS::AccountId

  AWSCURCrawlerComponentFunction:

    DependsOn: S3Bucket

    Type: 'AWS::IAM::Role'

    Properties:

      AssumeRolePolicyDocument:

        Version: 2012-10-17

        Statement:

          - Effect: Allow

            Principal:

              Service:

                - glue.amazonaws.com

            Action:

              - 'sts:AssumeRole'

      Path: /

      ManagedPolicyArns:

        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSGlueServiceRole'

      Policies:

        - PolicyName: AWSCURCrawlerComponentFunction

          PolicyDocument:

            Version: 2012-10-17

            Statement:

              - Effect: Allow

                Action:

                  - 'logs:CreateLogGroup'

                  - 'logs:CreateLogStream'

                  - 'logs:PutLogEvents'

                Resource: !Sub 'arn:${AWS::Partition}:logs:*:*:*'

              - Effect: Allow

                Action:

                  - 'glue:UpdateDatabase'

                  - 'glue:UpdatePartition'

                  - 'glue:CreateTable'

                  - 'glue:UpdateTable'

                  - 'glue:ImportCatalogToGlue'

                Resource: '*'

              - Effect: Allow

                Action:

                  - 's3:GetObject'

                  - 's3:PutObject'

                Resource: !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}/${S3Prefix}/${ReportName}/${ReportName}*'

  AWSCURCrawlerLambdaExecutor:

    Type: 'AWS::IAM::Role'

    Properties:

      AssumeRolePolicyDocument:

        Version: 2012-10-17

        Statement:

          - Effect: Allow

            Principal:

              Service:

                - lambda.amazonaws.com

            Action:

              - 'sts:AssumeRole'

      Path: /

      Policies:

        - PolicyName: AWSCURCrawlerLambdaExecutor

          PolicyDocument:

            Version: 2012-10-17

            Statement:

              - Effect: Allow

                Action:

                  - 'logs:CreateLogGroup'

                  - 'logs:CreateLogStream'

                  - 'logs:PutLogEvents'

                Resource: !Sub 'arn:${AWS::Partition}:logs:*:*:*'

              - Effect: Allow

                Action:

                  - 'glue:StartCrawler'

                Resource: '*'

  AWSCURCrawler:

    Type: 'AWS::Glue::Crawler'

    DependsOn:

      - AWSCURDatabase

      - AWSCURCrawlerComponentFunction

      - S3Bucket

    Properties:

      Name: AWSCURCrawler-AthenaCUR

      Description: A recurring crawler that keeps your CUR table in Athena up-to-date.

      Role: !GetAtt AWSCURCrawlerComponentFunction.Arn

      DatabaseName: !Ref AWSCURDatabase

      Targets:

        S3Targets:

          - Path: !Sub 's3://${S3Bucket}/${S3Prefix}/${ReportName}/${ReportName}'

            Exclusions:

              - '**.json'

              - '**.yml'

              - '**.sql'

              - '**.csv'

              - '**.gz'

              - '**.zip'

      SchemaChangePolicy:

        UpdateBehavior: UPDATE_IN_DATABASE

        DeleteBehavior: DELETE_FROM_DATABASE

  AWSCURInitializer:

    Type: 'AWS::Lambda::Function'

    DependsOn: AWSCURCrawler

    Properties:

      Code:

        ZipFile: >

          const AWS = require('aws-sdk');

          const response = require('./cfn-response');

          exports.handler = function(event, context, callback) {

            if (event.RequestType === 'Delete') {

              response.send(event, context, response.SUCCESS);

            } else {

              const glue = new AWS.Glue();

              glue.startCrawler({ Name: 'AWSCURCrawler-AthenaCUR' }, function(err, data) {

                if (err) {

                  const responseData = JSON.parse(this.httpResponse.body);

                  if (responseData['__type'] == 'CrawlerRunningException') {

                    callback(null, responseData.Message);

                  } else {

                    const responseString = JSON.stringify(responseData);

                    if (event.ResponseURL) {

                      response.send(event, context, response.FAILED,{ msg: responseString });

                    } else {

                      callback(responseString);

                    }

                  }

                }

                else {

                  if (event.ResponseURL) {

                    response.send(event, context, response.SUCCESS);

                  } else {

                    callback(null, response.SUCCESS);

                  }

                }

              });

            }

          };

      Handler: 'index.handler'

      Timeout: 30

      Runtime: nodejs12.x

      ReservedConcurrentExecutions: 1

      Role: !GetAtt AWSCURCrawlerLambdaExecutor.Arn

  AWSStartCURCrawler:

    Type: 'Custom::AWSStartCURCrawler'

    Properties:

      ServiceToken: !GetAtt AWSCURInitializer.Arn

  AWSS3CUREventLambdaPermission:

    DependsOn: S3Bucket

    Type: AWS::Lambda::Permission

    Properties:

      Action: 'lambda:InvokeFunction'

      FunctionName: !GetAtt AWSCURInitializer.Arn

      Principal: 's3.amazonaws.com'

      SourceAccount: !Ref AWS::AccountId

      SourceArn: !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}'

  AWSS3CURLambdaExecutor:

    DependsOn: S3Bucket

    Type: 'AWS::IAM::Role'

    Properties:

      AssumeRolePolicyDocument:

        Version: 2012-10-17

        Statement:

          - Effect: Allow

            Principal:

              Service:

                - lambda.amazonaws.com

            Action:

              - 'sts:AssumeRole'

      Path: /

      Policies:

        - PolicyName: AWSS3CURLambdaExecutor

          PolicyDocument:

            Version: 2012-10-17

            Statement:

              - Effect: Allow

                Action:

                  - 'logs:CreateLogGroup'

                  - 'logs:CreateLogStream'

                  - 'logs:PutLogEvents'

                Resource: !Sub 'arn:${AWS::Partition}:logs:*:*:*'

              - Effect: Allow

                Action:

                  - 's3:PutBucketNotification'

                Resource: !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}'

  AWSS3CURNotification:

    Type: 'AWS::Lambda::Function'

    DependsOn:

    - AWSCURInitializer

    - AWSS3CUREventLambdaPermission

    - AWSS3CURLambdaExecutor

    Properties:

      Code:

        ZipFile: >

          const AWS = require('aws-sdk');

          const response = require('./cfn-response');

          exports.handler = function(event, context, callback) {

            const s3 = new AWS.S3();

            const putConfigRequest = function(notificationConfiguration) {

              return new Promise(function(resolve, reject) {

                s3.putBucketNotificationConfiguration({

                  Bucket: event.ResourceProperties.BucketName,

                  NotificationConfiguration: notificationConfiguration

                }, function(err, data) {

                  if (err) reject({ msg: this.httpResponse.body.toString(), error: err, data: data });

                  else resolve(data);

                });

              });

            };

            const newNotificationConfig = {};

            if (event.RequestType !== 'Delete') {

              newNotificationConfig.LambdaFunctionConfigurations = [{

                Events: [ 's3:ObjectCreated:*' ],

                LambdaFunctionArn: event.ResourceProperties.TargetLambdaArn || 'missing arn',

                Filter: { Key: { FilterRules: [ { Name: 'prefix', Value: event.ResourceProperties.ReportKey } ] } }

              }];

            }

            putConfigRequest(newNotificationConfig).then(function(result) {

              response.send(event, context, response.SUCCESS, result);

              callback(null, result);

            }).catch(function(error) {

              response.send(event, context, response.FAILED, error);

              console.log(error);

              callback(error);

            });

          };

      Handler: 'index.handler'

      Timeout: 30

      Runtime: nodejs12.x

      ReservedConcurrentExecutions: 1

      Role: !GetAtt AWSS3CURLambdaExecutor.Arn

  AWSPutS3CURNotification:

    DependsOn:

      - S3Bucket

      - AWSCURInitializer

    Type: 'Custom::AWSPutS3CURNotification'

    Properties:

      ServiceToken: !GetAtt AWSS3CURNotification.Arn

      TargetLambdaArn: !GetAtt AWSCURInitializer.Arn

      BucketName: !Sub ${S3Bucket} # because of dependency ref is not working here

      ReportKey:  !Sub '${S3Prefix}/${ReportName}/${ReportName}'

  AWSCURReportStatusTable:

    Type: 'AWS::Glue::Table'

    DependsOn:

      - AWSCURDatabase

      - S3Bucket

    Properties:

      DatabaseName: !Ref GlueDatabaseName

      CatalogId: !Ref AWS::AccountId

      TableInput:

        Name: 'cost_and_usage_data_status'

        TableType: 'EXTERNAL_TABLE'

        StorageDescriptor:

          Columns:

            - Name: status

              Type: 'string'

          InputFormat: 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'

          OutputFormat: 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'

          SerdeInfo:

            SerializationLibrary: 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'

          Location: !Sub 's3://${S3Bucket}/${S3Prefix}/${ReportName}/cost_and_usage_data_status/'

Outputs:

  Bucket:

    Description: BucketName

    Value: !Ref S3Bucket