AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create an S3 bucket with access control for an AWS Organization, Organizational Unit, or single account.

Parameters:
  OrganizationId:
    Description: The ID of the AWS Organization to grant access to.
    Type: String
    Default: ''
  OrganizationalUnitId:
    Description: The ID of the AWS Organizational Unit to grant access to.
    Type: String
    Default: ''
  AccountId:
    Description: The AWS Account ID to grant access to.
    Type: String
    Default: ''

Conditions:
  UseOrganizationAccess: !Not [!Equals [!Ref OrganizationId, '']]
  UseOrganizationalUnitAccess: !Not [!Equals [!Ref OrganizationalUnitId, '']]
  UseSingleAccountAccess: !Not [!Equals [!Ref AccountId, '']]

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'my-bucket-${AWS::AccountId}-${AWS::Region}'

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${S3Bucket}'
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'
            Condition:
              StringEqualsIfExists:
                aws:PrincipalOrgID: !If [UseOrganizationAccess, !Ref OrganizationId, !Ref 'AWS::NoValue']
              StringLikeIfExists:
                aws:PrincipalOrgPaths: !If [UseOrganizationalUnitAccess, !Sub 'o-${OrganizationId}/ou-${OrganizationalUnitId}/*', !Ref 'AWS::NoValue']
              StringEqualsIfExists:
                aws:PrincipalAccount: !If [UseSingleAccountAccess, !Ref AccountId, !Ref 'AWS::NoValue']

Outputs:
  BucketName:
    Description: The name of the S3 bucket
    Value: !Ref S3Bucket
  BucketArn:
    Description: The ARN of the S3 bucket
    Value: !GetAtt S3Bucket.Arn