AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an AWS Amplify web application for a TodoApp.'

Resources:
  AmplifyApp:
    Type: 'AWS::Amplify::App'
    Properties:
      Name: 'TodoApp'
      Tags:
        - Key: 'Project'
          Value: 'TodoApp'

  AmplifyBranch:
    Type: 'AWS::Amplify::Branch'
    Properties:
      AppId: !Sub '${AmplifyApp.AppId}'
      BranchName: 'main'
      Stage: 'PRODUCTION'

Outputs:
  AmplifyAppURL:
    Description: 'The URL of the deployed AWS Amplify application.'
    Value: !Sub 'https://${AmplifyBranch.BranchName}.${AmplifyApp.DefaultDomain}'
  AmplifyAppArn:
    Description: 'The ARN of the AWS Amplify application.'
    Value: !GetAtt [AmplifyApp, Arn]