AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LogFilePrefix:
    Description: Optional prefix for log files in the S3 bucket
    Type: String
    Default: ''
  TrafficType:
    Description: Type of traffic to capture (ALL, ACCEPT, REJECT)
    Type: String
    AllowedValues: [ALL, ACCEPT, REJECT]
    Default: ALL

Resources:
  FlowLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FlowLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FlowLogsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceSSL
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: 
              - !Sub '${FlowLogsBucket.Arn}/*'
              - !Sub '${FlowLogsBucket.Arn}'
            Condition:
              Bool:
                aws:SecureTransport: false

  VPCFlowLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'vpc-flow-logs.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: VPCFlowLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 's3:PutObject'
                Resource: !Sub '${FlowLogsBucket.Arn}/*'
                Condition:
                  StringEquals:
                    s3:x-amz-acl: 'bucket-owner-full-control'

  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

  VPCFlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      DeliverLogsPermissionArn: !GetAtt VPCFlowLogsRole.Arn
      LogDestinationType: s3
      LogDestination: !Sub 'arn:aws:s3:::${FlowLogsBucket}/${LogFilePrefix}'
      ResourceId: !Ref MyVPC
      ResourceType: VPC
      TrafficType: !Ref TrafficType

Outputs:
  FlowLogsBucketName:
    Description: The name of the S3 bucket for VPC flow logs
    Value: !Ref FlowLogsBucket
  VPCId:
    Description: The ID of the created VPC
    Value: !Ref MyVPC