AWSTemplateFormatVersion: '2010-09-09'
Description: Multi-AZ, Load Balanced, and Auto-Scaled Apache Web Server
Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP traffic
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-0c55b31ad2299a701
      InstanceType: t2.micro
      KeyName: MyKeyPair
      SecurityGroups:
      - !Ref WebServerSecurityGroup
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install httpd -y
        service httpd start
        chkconfig httpd on
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref LaunchConfiguration
      MinSize: 1
      MaxSize: 4
      VPCZoneIdentifier:
      - !Select [0, !GetAZs '']
      - !Select [1, !GetAZs '']
      - !Select [2, !GetAZs '']
      HealthCheckType: EC2
      NotificationConfigurations:
      - TopicARN: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:MySNSTopic
        NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
      ScalingPolicies:
      - AdjustmentType: PercentChangeInCapacity
        AutoScalingGroupName: !Ref AutoScalingGroup
        Cooldown: 60
        MetricAggregationType: Average
        MinAdjustmentStep: 1
        ScalingAdjustment: 20
        StepAdjustments:
        - MetricIntervalLowerBound: 0
          MetricIntervalUpperBound: 50
          ScalingAdjustment: 0
        - MetricIntervalLowerBound: 50
          MetricIntervalUpperBound: 80
          ScalingAdjustment: 1
        - MetricIntervalLowerBound: 80
          MetricIntervalUpperBound: 100
          ScalingAdjustment: 2
        ScalingPolicyName: ScaleUpCPU
        StepScalingPolicyConfiguration:
          AdjustmentType: PercentChangeInCapacity
          Cooldown: 60
          MetricAggregationType: Average
          MinAdjustmentMagnitude: 1
          StepAdjustments:
          - MetricIntervalLowerBound: 0
            MetricIntervalUpperBound: 50
            ScalingAdjustment: 0
          - MetricIntervalLowerBound: 50
            MetricIntervalUpperBound: 80
            ScalingAdjustment: 1
          - MetricIntervalLowerBound: 80
            MetricIntervalUpperBound: 100
            ScalingAdjustment: 2
        AdjustmentType: PercentChangeInCapacity
        AutoScalingGroupName: !Ref AutoScalingGroup
        Cooldown: 60
        MetricAggregationType: Average
        MinAdjustmentStep: -1
        ScalingAdjustment: -10
        StepAdjustments:
        - MetricIntervalLowerBound: 0
          MetricIntervalUpperBound: 20
          ScalingAdjustment: 0
        - MetricIntervalLowerBound: 20
          MetricIntervalUpperBound: 50
          ScalingAdjustment: -1
        - MetricIntervalLowerBound: 50
          MetricIntervalUpperBound: 100
          ScalingAdjustment: -2
        ScalingPolicyName: ScaleDownCPU
        StepScalingPolicyConfiguration:
          AdjustmentType: PercentChangeInCapacity
          Cooldown: 60
          MetricAggregationType: Average
          MinAdjustmentMagnitude: 1
          StepAdjustments:
          - MetricIntervalLowerBound: 0
            MetricIntervalUpperBound: 20
            ScalingAdjustment: 0
          - MetricIntervalLowerBound: 20
            MetricIntervalUpperBound: 50
            ScalingAdjustment: -1
          - MetricIntervalLowerBound: 50
            MetricIntervalUpperBound: 100
            ScalingAdjustment: -2
      - AdjustmentType: PercentChangeInCapacity
        AutoScalingGroupName: !Ref AutoScalingGroup
        Cooldown: 60
        MetricAggregationType: Average
        MinAdjustmentStep: 1
        ScalingAdjustment: 20
        StepAdjustments:
        - MetricIntervalLowerBound: 0
          MetricIntervalUpperBound: 50
          ScalingAdjustment: 0
        - MetricIntervalLowerBound: 50
          MetricIntervalUpperBound: 80
          ScalingAdjustment: 1
        - MetricIntervalLowerBound: 80
          MetricIntervalUpperBound: 100
          ScalingAdjustment: 2
        ScalingPolicyName: ScaleUpCPU
        StepScalingPolicyConfiguration:
          AdjustmentType: PercentChangeInCapacity
          Cooldown: 60
          MetricAggregationType: Average
          MinAdjustmentMagnitude: 1
          StepAdjustments:
          - MetricIntervalLowerBound: 0
            MetricIntervalUpperBound: 50
            ScalingAdjustment: 0
          - MetricIntervalLowerBound: 50
            MetricIntervalUpperBound: 80
            ScalingAdjustment: 1
          - MetricIntervalLowerBound: 80
            MetricIntervalUpperBound: 100
            ScalingAdjustment: 2
  LoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      HealthCheck:
        HealthyThreshold: 2
        Interval: 30
        Target: HTTP:80
        Timeout: 5
        UnhealthyThreshold: 2
      Listeners:
      - InstancePort: 80
        LoadBalancerPort: 80
        Protocol: HTTP
      Instances:
      - !Ref AutoScalingGroup
      Subnets:
      - !Select [0, !GetAZs '']
      - !Select [1, !GetAZs '']
      - !Select [2, !GetAZs '']
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: MySNStopic
      Subscription:
      - Endpoint: your_email@example.com
        Protocol: email
      TopicName: MySNSTopic

Outputs:
  LoadBalancerDNSName:
    Value: !GetAtt LoadBalancer.DNSName
    Description: The DNS name of the load balancer