AWSTemplateFormatVersion: 2010-09-09
Resources:
  Bucket:
    Type: AWS::S3::Bucket
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:GetObject
            Principal: '*'
            Resource: !Sub 'arn:aws:s3:::${Bucket}/*'
          - Effect: Allow
            Action: s3:ListBucket
            Principal: '*'
            Resource: !Sub 'arn:aws:s3:::${Bucket}'
Outputs:
  BucketName:
    Value: !Ref Bucket
    Export:
      Name: !Sub "${AWS::StackName}:BucketName"
  BucketArn:
    Value: !GetAtt Bucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}:BucketArn"
  DomainName:
    Value: !GetAtt Bucket.DomainName
    Export:
      Name: !Sub "${AWS::StackName}:DomainName"