AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SecurityHub:
    Type: AWS::SecurityHub::Hub
    Properties:
      EnableDefaultStandards: true
      EnableSecurityHub: true
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
Outputs:
  SecurityHubAccountId:
    Description: The AWS Account ID associated with the Security Hub
    Value: !GetAtt SecurityHub.AccountId
    Export:
      Name: SecurityHub-AccountId
  SecurityHubArn:
    Description: The ARN of the Security Hub
    Value: !GetAtt SecurityHub.HubArn
    Export:
      Name: SecurityHub-ARN