AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      DisplayName: "Test Notification Topic"
  SNSEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: test@test.com
      TopicArn: !Ref SNSTopic
Outputs:
  SNSTopicARN:
    Description: ARN of the SNS Topic
    Value: !Ref SNSTopic
    Export:
      Name: !Sub "${AWS::StackName}-SNSTopicARN"