AWSTemplateFormatVersion: "2010-09-09"
Description: >-
    Last Modified: 2025/11/25 17:06:37
    "RADx Secrets Manager stack"
    Please ensure to update secrets with secure values."

Parameters:
    Environment:
        Type: String
        Description: The Project Environment
        AllowedValues:
            - dev
            - test
            - prod
            - shared
    ProjectName:
        Type: String
        Description: The Project name
        Default: radx
        AllowedValues:
            - radx
    PostgresMasterUsername:
        Type: String
        Description: RDS master username
    PostgresMasterPassword:
        Type: String
        NoEcho: true
        Description: RDS master password
    RadxAdminUsername:
        Type: String
        Description: RADx admin username
    RadxAdminPassword:
        Type: String
        NoEcho: true
        Description: RADx admin password
    RadxUserUsername:
        Type: String
        Description: RADx application user username
    RadxUserPassword:
        Type: String
        NoEcho: true
        Description: RADx application user password
    OpenSearchHostname:
        Type: String
        Description: OpenSearch domain endpoint hostname (e.g., search-...us-east-1.es.amazonaws.com)
    OpenSearchUsername:
        Type: String
        Description: OpenSearch master username
        MinLength: 3
        MaxLength: 64
        AllowedPattern: "[a-zA-Z0-9_+=.@-]+"
    OpenSearchPassword:
        Type: String
        NoEcho: true
        Description: OpenSearch master password
        MinLength: 8
        MaxLength: 128
    AppDBUsername:
        Type: String
        Description: Application DB user (e.g., radx_user)
    AppDBPassword:
        Type: String
        NoEcho: true
        Description: Application DB password

Conditions:
  DEV: !Equals [!Ref Environment, dev]
  TEST: !Equals [!Ref Environment, test]
  PROD: !Equals [!Ref Environment, prod]
  NOTDEV: !Not [!Equals [!Ref Environment, dev]]
  NOTPROD: !Not [!Equals [!Ref Environment, prod]]

Resources:

    RDSMasterSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name: !Sub "rds/radxpostgres${Environment}/${Environment}"
            Description: !Sub "Default Secret associated with primary RDS DB instance: arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:radx-postgresql-${Environment}"
            SecretString: !Sub '{"username":"${PostgresMasterUsername}","password":"${PostgresMasterPassword}"}'

    RDSAdminSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name: !Sub "rds/radx_admin/${Environment}"
            Description: "Access to production credentials"
            SecretString: !Sub '{"username":"${RadxAdminUsername}","password":"${RadxAdminPassword}"}'

    RDSUserSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name: !Sub "rds/radx_user/${Environment}"
            SecretString: !Sub '{"username":"${RadxUserUsername}","password":"${RadxUserPassword}"}'

    ApplicationSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name:
                !Sub  "application_${Environment}"
            Description: !Sub "Secret associated with primary RDS DB instance: arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:radx-prod-postgresql"
            SecretString: !Sub |
                {
                    "dbuser":"${RadxUserUsername}",
                    "password":"${RadxUserPassword}",
                    "engine":"postgres",
                    "host":"TBD", ## RDS Proxy Endpoint
                    "port":"5432",
                    "dbname":"RADx_prod",
                    "dbInstanceIdentifier":"radx-prod-postgresql",
                    "opensearch.hostname":"${OpenSearchHostname}", ## OpenSearch Endpoint
                    "opensearch.port":"443",
                    "opensearch.scheme":"https",
                    "opensearch.username":"${OpenSearchUsername}",
                    "opensearch.password":"${OpenSearchPassword}",
                    "supportEmail":"**@nih.gov,", ## Support Email
                    "gmailPassword":"Not Applicable",
                    "WorkbenchBucketBaseName":"sagemaker-prod-",
                    "rasclientid":"TBD", ## RAS Client ID
                    "rasclientsecret":"TBD", ## RAS Client Secret
                    "redirecturl":"https://radxdatahub.nih.gov/api/user/v1/ras", ## Redirect URL
                    "GA1PropertyId":"341918636", ## GA1 Property ID
                    "GACredentials": "{\"type\": \"service_account\",\"project_id\": \"radx-datahub-ga4\",\"private_key_id\": \"REPLACEME\",\"private_key\": \"REPLACEME\\n\",\"client_email\": \"analytics-prod@radx-datahub-ga4.iam.gserviceaccount.com\",\"client_id\": \"REPLACEME\",\"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\"token_uri\": \"https://oauth2.googleapis.com/token\",\"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/analytics-prod@radx-datahub-ga4.iam.gserviceaccount.com\",\"universe_domain\": \"googleapis.com\"}",
                    "EmailQueue":"prodEmailQueue",
                    "rasurl":"https://sts.nih.gov",
                    "InReviewS3Bucket":"covid-radx-review",
                    "ApprovedS3Bucket":"covid-radx-default",
                    "MtaFormBucket":"prod-covid-radx-ingest-pdf",
                    "PiiQueue":"pii-sqs-queue-prod",
                    "SFTPQueue":"sftp-queue-prod",
                    "SFTPIngestBucket":"sftp-radx",
                    "HostURL":"https://radxdatahub.nih.gov",
                    "sagemakerurl":"https://**.lambda-url.us-west-2.on.aws",
                    "StakeholderEmailsWorkbenchSubmit":"**@nih.gov,",
                    "StakeholderEmailsStudyReg":"",
                    "VariablesPagePath":"radxdatahub.nih.gov/variables-explorer/Variables-Page.xlsx",
                    "VariablesReportPath":"radxdatahub.nih.gov/variables-explorer/Complete-Data-Variable-Report.xlsx",
                    "UuidSpreadsheetPath":"radxdatahub.nih.gov/radx-s3-resources/RADx-Data-Hub_Study-IDs.xlsx",
                    "DataCiteUrl":"https://api.datacite.org/dois","DataCiteUser":"TBD",
                    "DataCitePassword":"TBD",
                    "DataCitePrefix":"10.60773",
                    "accountId":"<AWS_ACCOUNT_ID>",
                    "StepFunctionMachineArn":"arn:aws:states:us-west-2:<AWS_ACCOUNT_ID>:stateMachine:polling-macie-job",
                    "rasauth":"https://sts.nih.gov/auth/oauth/v2/authorize?client_id=******&prompt=login+consent&redirect_uri=https://radxdatahub.nih.gov/api/user/v1/ras&response_type=code&scope=openid+email+profile+ga4gh_passport_v1+department",
                    "StakeholderEmailsWorkbenchAction":"**@nih.gov,",
                    "apikey":"TBD",
                    "ResourceBucket":"radxdatahub.nih.gov",
                    "WeeklyReportPath":"radx-s3-resources/RADx-DataHub-Weekly-Metrics.csv",
                    "WeeklyReportFileName":"RADx-DataHub-Weekly-Metrics.csv",
                    "UploadPortalBucket":"radx-upload-portal-prod"
                }