Transform: AWS::Serverless-2016-10-31
Resources:
  Fn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.12
      CodeUri: s3://bucket/key.zip
      DeadLetterQueue:
        TargetArn: arn:aws:sqs:us-east-1:123456789012:queue