AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  anything-dash

Parameters:
  stage:
    Type: String
    Default: dev-123
    Description: Deployment stage with unique key, like "dev-123"

Resources:
  dataBucketArn:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Tier: Standard
      Value:
        Fn::ImportValue: !Sub "anything-${stage}-dataBucketArn" # OK

  queryResultsBucketArn:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Tier: Standard
      Value:
        Fn::ImportValue: !Sub "anything-${stage}-queryResultsBucketArn" # OK

  glueDatabase:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Tier: Standard
      Value:
        Fn::ImportValue: !Sub "anything-${stage}-glueDatabase" # OK

  glueMainTable:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Tier: Standard
      Value:
        Fn::ImportValue: !Sub "anything-${stage}-glueMainTable" # OK

  athenaWorkgroup:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Tier: Standard
      Value:
        Fn::ImportValue: !Sub "anything-${stage}-athenaWorkgroup" # OK

  GrafanaUser:
    Type: AWS::IAM::User
    Properties:
      Path: '/anything/users/'

  GrafanaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "anything-${stage}-grafana-role"
      Path: '/anything/roles/' # becomes for ex: anything/roles/anything-dash-dev-grafana-role
      Description: 'Role for Grafana dashboard'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              AWS: !GetAtt GrafanaUser.Arn
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub "anything-${stage}-grafana-policy"
          # ref: https://github.com/grafana/athena-datasource
          # ref: https://docs.aws.amazon.com/grafana/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AmazonGrafanaAthenaAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # ref: https://docs.aws.amazon.com/athena/latest/ug/example-policies-workgroup.html
              - Sid: "AthenaAccess"
                Effect: "Allow"
                Action:
                  - "athena:ListDatabases"
                  - "athena:ListDataCatalogs"
                  - "athena:ListWorkGroups"
                  - "athena:GetDatabase"
                  - "athena:GetDataCatalog"
                  - "athena:GetTableMetadata"
                  - "athena:ListTableMetadata"
                  - "athena:GetWorkGroup"
                Resource:
                  - !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:*
              - Sid: "AthenaWorkgroupAccess"
                Effect: "Allow"
                Action:
                  - "athena:GetQueryExecution"
                  - "athena:GetQueryResults"
                  - "athena:StartQueryExecution"
                  - "athena:StopQueryExecution"
                Resource:
                  - !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${athenaWorkgroup}
              - Sid: "GlueReadAccess"
                Effect: "Allow"
                Action:
                  - "glue:GetDatabase"
                  - "glue:GetDatabases"
                  - "glue:GetTable"
                  - "glue:GetTables"
                  - "glue:GetPartition"
                  - "glue:GetPartitions"
                  - "glue:BatchGetPartition"
                Resource:
                  # ref: https://docs.aws.amazon.com/glue/latest/dg/glue-specifying-resource-arns.html
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${glueDatabase}
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${glueDatabase}/${glueMainTable}
              - Sid: "QueryBucketAccess"
                Effect: "Allow"
                Action:
                  - "s3:GetBucketLocation"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "s3:ListBucketMultipartUploads"
                  - "s3:ListMultipartUploadParts"
                  - "s3:AbortMultipartUpload"
                  - "s3:PutObject"
                Resource:
                  - !GetAtt queryResultsBucketArn.Value
                  - !Sub "${queryResultsBucketArn.Value}/*"
              - Sid: "DataBucketAccess"
                Effect: "Allow"
                Action:
                  - "s3:GetBucketLocation"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "s3:ListBucketMultipartUploads"
                  - "s3:ListMultipartUploadParts"
                Resource:
                  - !GetAtt dataBucketArn.Value
                  - !Sub "${dataBucketArn.Value}/*"