AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda Multi-region authorizer

Globals:
  Function:
    Timeout: 10

Parameters:
  HostedZoneId:
    Type: String
    Description: The Route53 Hosted Zone ID
    Default: "<< HOSTED ZONE ID - Z01235..XXX >>"
  DomainName:
    Type: String
    Description: The custom domain name for the API Gateway
    Default: "<< DOMAIN NAME - authorizer.example.com >>"
  PrimaryApiDomainName:
    Type: String
    Description: Custom domain name from the API GW custom domain name
    Default: "<< PRIMARY API DOMAIN NAME d-XXX.execute-api.us-east-1.amazonaws.com"
  PrimaryApiHostedZoneId:
    Type: String
    Description: Hosted zone ID from the API GW
    Default: "<< PRIMARY HOSTED ZONE ID >>"
  SecondaryApiDomainName:
    Type: String
    Description: Custom domain name from the API GW custom domain name
    Default: "<< SECONDARY API DOMAIN NAME - d-YYYY.execute-api.us-west-2.amazonaws.com"
  SecondaryApiHostedZoneId:
    Type: String
    Description: Hosted zone ID from the API GW
    Default: "<< SECONDARY HOSTED ZONE ID >>"

Resources:

  Route53HealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        FailureThreshold: 2
        FullyQualifiedDomainName: !Ref DomainName
        Port: 443
        RequestInterval: 10
        ResourcePath: /failure
        Type: HTTPS
      HealthCheckTags:
        - Key: Environment
          Value: Production
        - Key: Name
          Value: multi-authorizer-health-check

  PrimaryRoute53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !Ref PrimaryApiDomainName
        HostedZoneId: !Ref PrimaryApiHostedZoneId
        EvaluateTargetHealth: true
      SetIdentifier: primary
      HealthCheckId: !Ref Route53HealthCheck
      Failover: PRIMARY

  SecondaryRoute53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !Ref SecondaryApiDomainName
        HostedZoneId: !Ref SecondaryApiHostedZoneId
      SetIdentifier: secondary
      Failover: SECONDARY