AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation Template to deploy an EC2 instance (t3.micro) with AWS Systems Manager (SSM)
  enabled for secure remote management. This template creates a basic network infrastructure including a VPC and a subnet,
  then deploys a minimal security group and an EC2 instance with a region-specific AMI and SSM enabled.

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c94855ba95c71c99
    us-east-2:
      AMI: ami-0703c9afc4e1c3fa3
    us-west-1:
      AMI: ami-0bdb828fd58c52235
    us-west-2:
      AMI: ami-062f7200baf2fa504

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: SSM-VPC

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.0.0/24"
      AvailabilityZone: !Select 
        - 0
        - !GetAZs ""
      Tags:
        - Key: Name
          Value: SSM-Subnet

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Minimal Security Group for EC2 instance with secure SSM access."
      VpcId: !Ref VPC
      SecurityGroupIngress: []
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: SSM-Managed-Instance-SG

  SSMInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: SSMInstanceRole

  SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref SSMInstanceRole

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !FindInMap
        - RegionMap
        - !Ref "AWS::Region"
        - AMI
      IamInstanceProfile: !Ref SSMInstanceProfile
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref Subnet
      Tags:
        - Key: Name
          Value: SSM-Managed-EC2Instance

Outputs:
  InstanceId:
    Description: "The Instance ID of the EC2 instance."
    Value: !Ref EC2Instance
  VPCId:
    Description: "The VPC ID created for the network."
    Value: !Ref VPC
  SubnetId:
    Description: "The Subnet ID in which the instance is launched."
    Value: !Ref Subnet