AWSTemplateFormatVersion: "2010-09-09"
Description: Lab 7.6 — ACM public certificate request (will sit in PENDING_VALIDATION without DNS delegation)

Resources:
  PublicCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: dva-lab-07-06.example.com
      SubjectAlternativeNames:
        - www.dva-lab-07-06.example.com
      ValidationMethod: DNS

Outputs:
  CertArn:
    Value: !Ref PublicCert