AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 30

  MyTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: IoTDataTopic

  IoTDataRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: DeviceDataRule
      TopicRulePayload:
        Actions:
          - Sns:
              TopicArn: !Ref MyTopic
          - Sqs:
              QueueUrl: !Ref MyQueue
        AwsIotSqlVersion: "2016-03-31"
        Sql: "SELECT * FROM 'device/data'"

Outputs:
  QueueURL:
    Value: !Ref MyQueue
  TopicARN:
    Value: !Ref MyTopic