AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Stage:
    Type: String
    Default: CODE
    AllowedValues:
      - PROD
      - CODE

Resources:
  SupporterProductDataPROD:
    Type: AWS::DynamoDB::Table
    Condition: IsProd
    Properties:
      TableName: SupporterProductDataPROD
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 20
        WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: expiryDate
      Tags:
        - Key: backup
          Value: 'true'

  SupporterProductDataCODE:
    Type: AWS::DynamoDB::Table
    Condition: IsCode
    Properties:
      TableName: SupporterProductDataCODE
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: expiryDate
      Tags:
        - Key: backup
          Value: 'true'

  WriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: IsProd
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: !Join
        - '/'
        - - table
          - !Ref SupporterProductDataPROD
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      MinCapacity: 5
      MaxCapacity: 500
      RoleARN: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/DynamoDBAutoscaleRole'

  WriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: IsProd
    Properties:
      PolicyName: SupporterProductDataPROD-WriteScaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization

Conditions:
  IsProd: !Equals [!Ref Stage, 'PROD']
  IsCode: !Equals [!Ref Stage, 'CODE']

Outputs:
  PRODTableName:
    Value: !Ref SupporterProductDataPROD
    Condition: IsProd
  CODETableName:
    Value: !Ref SupporterProductDataCODE
    Condition: IsCode