#!/usr/bin/env python3
import csv,collections,os,datetime
results_csv=os.path.expanduser('~/iac-benchmark/outputs/results_summary.csv')
report_path=os.path.expanduser('~/iac-benchmark/report.md')
rows=[]
with open(results_csv,newline='') as f:
    reader=csv.DictReader(f)
    for r in reader:
        rows.append(r)
# totals
total=len(rows)
pass_yaml=sum(1 for r in rows if r['yaml_gate']=='✅')
pass_lint=sum(1 for r in rows if r['cfn_lint_gate']=='✅')
overall_pass=sum(1 for r in rows if r['overall_status'].strip().startswith('✅'))
# most common error
counter=collections.Counter()
for r in rows:
    if r['error_summary']:
        # try to extract rule id like W3045 or E3002
        import re
        m=re.search(r'([WE]\d{4})', r['error_summary'])
        if m:
            counter[m.group(1)]+=1
        else:
            # fallback: take first word
            counter[r['error_summary'].split()[0]]+=1
most_common = counter.most_common(1)[0][0] if counter else '—'
# write report
with open(report_path,'w') as out:
    out.write('# IaCGen Benchmark Report\n\n')
    out.write('Run date: '+datetime.datetime.utcnow().isoformat()+'Z\n')
    out.write('Model: generate_cfn (skill)\n')
    out.write('Skills used: generate_cfn, validate_cfn\n')
    out.write('Live deployment: skipped (skip_deploy=true)\n')
    out.write('Total prompts: 153\n\n')
    out.write('***\n\n')
    out.write('## Results Table\n\n')
    out.write('| Row | Ground Truth Template | Status | YAML | cfn-lint | Deploy | Error Summary |\n')
    out.write('|-----|-----------------------|--------|------|----------|--------|---------------|\n')
    for r in rows:
        rownum=r['row']
        gt=os.path.basename(r['ground_truth_path']) if r['ground_truth_path'] else ''
        out.write(f"| {rownum} | {gt} | {r['overall_status']} | {r['yaml_gate']} | {r['cfn_lint_gate']} | {r['deploy_gate']} | {r['error_summary'] or '—'} |\n")
    out.write('\n***\n\n')
    out.write('## Summary Statistics\n\n')
    out.write('| Metric | Value |\n')
    out.write('|--------|-------|\n')
    out.write(f'| Total prompts | {total} |\n')
    out.write(f'| ✅ Overall passed (YAML + cfn-lint) | {overall_pass} |\n')
    out.write(f'| ❌ Overall failed | {total-overall_pass} |\n')
    out.write(f'| Overall pass rate | {overall_pass/total*100:.1f}% |\n')
    out.write(f'| ✅ YAML syntax passed | {pass_yaml} |\n')
    out.write(f'| ✅ cfn-lint passed | {pass_lint} |\n')
    out.write(f'| Most common error type | {most_common} |\n')
    out.write('\n***\n\n')
    out.write('## Failure Analysis\n\n')
    yaml_errs=[]
    lint_errs=[]
    unknown=[]
    for r in rows:
        if r['overall_status'].strip().startswith('❌'):
            if r['yaml_gate']=='❌':
                yaml_errs.append((r['row'],r['error_summary']))
            elif r['cfn_lint_gate']=='❌':
                lint_errs.append((r['row'],r['error_summary']))
            else:
                unknown.append((r['row'],r['error_summary']))
    out.write('### YAML Syntax Errors\n')
    for a,b in yaml_errs:
        out.write(f'- Row {a}: {b}\n')
    out.write('\n### cfn-lint Errors\n')
    for a,b in lint_errs:
        out.write(f'- Row {a}: {b}\n')
    out.write('\n### Unknown / Parse Failures\n')
    for a,b in unknown:
        out.write(f'- Row {a}: {b}\n')
    out.write('\n***\n\n')
    out.write('## Notes\n')
    out.write('- Report generated by parse_and_report.py from results_summary.csv\n')
print('WROTE',report_path)
