AWSTemplateFormatVersion: "2022-02-24"

Description: This template create VPC with public and private subnets

Metadata:

Parameters:
  VpcCIDR:
    Default: 10.0.0.0/16
    Description: Please Enter the IP Range (Cidr notation) for this VPC.
    Type: String

  PublicSubnet1CIDR:
    Default: 10.0.0.0/24
    Description: Please Enter the IP Range (Cidr notation) for this public subnet 1
    Type: String

  PublicSubnet2CIDR:
    Default: 10.1.0.0/24
    Description: Please Enter the IP Range (Cidr notation) for this public subnet 2
    Type: String

  PrivateSubnet1CIDR:
    Default: 10.2.0.0/24
    Description: Please Enter the IP Range (Cidr notation) for this private subnet 1
    Type: String

  PrivateSubnet2CIDR:
    Default: 10.3.0.0/24
    Description: Please Enter the IP Range (Cidr notation) for this private subnet 2
    Type: String

  PrivateSubnet3CIDR:
    Default: 10.4.0.0/24
    Description: Please Enter the IP Range (Cidr notation) for this private subnet 3
    Type: String

  PrivateSubnet4CIDR:
    Default: 10.5.0.0/24
    Description: Please Enter the IP Range (Cidr notation) for this private subnet 4
    Type: String

Resources:

Outputs: