AWSTemplateFormatVersion: '2010-09-09'
Description: SNS-to-SQS Fanout System with Filtered Message Routing

Parameters:
  Region:
    Type: String
    Default: us-east-1
    Description: AWS Region where resources will be deployed

Resources:
  TemperatureSqsQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: TemperatureSqsQueueDLQ
      MessageRetentionPeriod: 345600

  HumiditySqsQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: HumiditySqsQueueDLQ
      MessageRetentionPeriod: 345600

  AllMetricsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: AllMetricsQueue
      MessageRetentionPeriod: 345600

  TemperatureSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: TemperatureSqsQueue
      MessageRetentionPeriod: 345600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TemperatureSqsQueueDLQ.Arn
        maxReceiveCount: 5

  HumiditySqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: HumiditySqsQueue
      MessageRetentionPeriod: 345600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt HumiditySqsQueueDLQ.Arn
        maxReceiveCount: 5

  MetricsFanoutTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MetricsFanoutTopic

  SnsToSqsPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref MetricsFanoutTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: sns.amazonaws.com }
            Action:
              - SQS:SendMessage
            Resource:
              - !GetAtt AllMetricsQueue.Arn
              - !GetAtt TemperatureSqsQueue.Arn
              - !GetAtt HumiditySqsQueue.Arn

  TemperatureSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref MetricsFanoutTopic
      Protocol: sqs
      Endpoint: !GetAtt TemperatureSqsQueue.Arn
      FilterPolicy:
        MetricType:
          - Temperature

  HumiditySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref MetricsFanoutTopic
      Protocol: sqs
      Endpoint: !GetAtt HumiditySqsQueue.Arn
      FilterPolicy:
        MetricType:
          - Humidity

  AllMetricsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref MetricsFanoutTopic
      Protocol: sqs
      Endpoint: !GetAtt AllMetricsQueue.Arn

Outputs:
  MetricsFanoutTopicArn:
    Description: ARN of the SNS topic
    Value: !Ref MetricsFanoutTopic
  AllMetricsQueueUrl:
    Description: URL of the AllMetricsQueue
    Value: !Ref AllMetricsQueue
  TemperatureSqsQueueUrl:
    Description: URL of the TemperatureSqsQueue
    Value: !Ref TemperatureSqsQueue
  HumiditySqsQueueUrl:
    Description: URL of the HumiditySqsQueue
    Value: !Ref HumiditySqsQueue