AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SecurityHub:
    Type: AWS::SecurityHub::Hub
    Properties:
      EnableDefaultStandards: true
      AutoEnableControls: true
Outputs:
  SecurityHubArn:
    Description: The ARN of the Security Hub
    Value: !GetAtt SecurityHub.Arn
  EnabledStandards:
    Description: The enabled security standards
    Value: !Join [",", !GetAtt SecurityHub.EnabledStandards]