---
## Amazon Aurora PostgreSQL Database Activity Walktrough
## Creates Aurora PostgreSQL Cluster, Cloud9 IDE instance
##
## Changelog:
##
## Dependencies:
## none
##
## This sample code is made available under the MIT-0 license. See the LICENSE file.

AWSTemplateFormatVersion: 2010-09-09
Description: Aurora/PG Database Activity Streams Walkthrough

# Parameters
Parameters:
  TemplateName:
    Type: String
    Default: dasblog-walkthrough
    Description: Name used for different elements created.
  TemplateURLBase:
    Type: String
    Default: https://dasblog-templates2.s3.amazonaws.com
    Description: Bucket holding the cloudformation template

## Resources
Resources:

# Create the VPC
  dasblogwalkthroughVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # TemplateURL: https://dasblog-template.s3.amazonaws.com/dasblog-aurora-vpc.yml
      TemplateURL: !Sub ${TemplateURLBase}/cloudformation/dasblog-aurora-vpc.yml
      Parameters:
        TemplateName: !Ref TemplateName

# Create the RDS Cluster
  dasblogwalkthroughRDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:

      TemplateURL: !Sub ${TemplateURLBase}/cloudformation/dasblog-aurora-cluster.yml
      Parameters:
          PubSubnetCidr: !GetAtt 'dasblogwalkthroughVPCStack.Outputs.PublicSubnetACidr'
          TemplateName: !Ref TemplateName
          MainVPC: !GetAtt dasblogwalkthroughVPCStack.Outputs.MainVPC
          PrivateSubnets: !GetAtt 'dasblogwalkthroughVPCStack.Outputs.PrivateSubnets'

# Create the Cloud9 Environment
  dasblogwalkthroughC9Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateURLBase}/cloudformation/dasblog-aurora-cloud9.yml
      Parameters:
          PubSubnetId: !GetAtt 'dasblogwalkthroughVPCStack.Outputs.PublicSubnetA'
          TemplateName: !Ref TemplateName
          # EnvType: !Ref EnvType

# Create the CMK
  dasblogwalkthroughCMK:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateURLBase}/cloudformation/dasblog-aurora-cmk-role.yml
      Parameters:
        TemplateName: !Ref TemplateName

# Create an S3 Bucket
  DASDataBucket:
      Type: "AWS::S3::Bucket"
      DeletionPolicy: Delete

# Outputs
Outputs:
  WalkthroughVPC:
    Description: Aurora PostgreSQL Lab VPCaupglabsRDSStack
    Value: !GetAtt dasblogwalkthroughVPCStack.Outputs.MainVPC
  Cloud9URL:
    Description: Cloud9 URL
    Value: !GetAtt dasblogwalkthroughC9Stack.Outputs.Cloud9URL
  DBSecGroup:
    Description: Database Security Group
    Value: !GetAtt dasblogwalkthroughRDSStack.Outputs.dbSecGroupCluster
  clusterEndpoint:
    Description: Aurora Cluster Endpoint
    # Value: !If [WithInstance, !GetAtt dasblogwalkthroughRDSStack.Outputs.clusterEndpoint, '']
    Value: !GetAtt dasblogwalkthroughRDSStack.Outputs.clusterEndpoint
  readerEndpoint:
    Description: Aurora Reader Endpoint
    # Value: !If [WithInstance, !GetAtt dasblogwalkthroughRDSStack.Outputs.readerEndpoint, '']
    Value: !GetAtt dasblogwalkthroughRDSStack.Outputs.readerEndpoint
  Port:
    Description: Aurora Endpoint Port
    # Value: !If [WithInstance, !GetAtt dasblogwalkthroughRDSStack.Outputs.Port, '']
    Value: !GetAtt dasblogwalkthroughRDSStack.Outputs.Port
  DatabaseName:
    Description: Database Name
    # Value: !If [WithInstance, !GetAtt dasblogwalkthroughRDSStack.Outputs.DatabaseName, '']
    Value: !GetAtt dasblogwalkthroughRDSStack.Outputs.DatabaseName
  secretArn:
    Description: Database Credentials Secret ARN
    Value: !GetAtt dasblogwalkthroughRDSStack.Outputs.secretArn
  DBUsername:
    Description: Database master username
    Value: !GetAtt dasblogwalkthroughRDSStack.Outputs.DBUsername
  DASS3Bucket:
    Description: "This is the bucket for writing out the DAS files"
    Value: !Ref 'DASDataBucket'
  DASS3BucketArn:
    Description: "This is the bucket for writing out the DAS files"
    Value: !GetAtt DASDataBucket.Arn

  DASCMKKeyID:
    Description: "This is the KMS Key ID"
    Value: !GetAtt dasblogwalkthroughCMK.Outputs.CMKKeyID
  DASCMKKeyArn:
    Description: "This is the KMS Key ID"
    Value: !GetAtt dasblogwalkthroughCMK.Outputs.CMKArn
  DASLambdaRoleArn:
    Description: 'Role Used for Lambda'
    Value: !GetAtt dasblogwalkthroughCMK.Outputs.LambdaRoleArn
  DBClusterId:
    Description: Cluster resource ARN
    Value: !GetAtt dasblogwalkthroughRDSStack.Outputs.DBClusterId