AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Bad port range
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 80
          CidrIp: 10.0.0.0/8