AWSTemplateFormatVersion: 2010-09-09
Parameters:
  LinuxAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2'
  InstanceType:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /cf-demos/ssm-params/default-instance-type

Resources:
  EC2WithPubSSMParam:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LinuxAmiId
      InstanceType: !Ref InstanceType