AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: S3ObjectCreatedNotifications

  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        detail:
          eventName:
            - "ObjectCreated:*"
      Targets:
        - Arn: !Ref SNSTopic
          Id: S3ObjectCreatedTarget