AWSTemplateFormatVersion: '2010-09-09'
Resources:
  B2BIPipelineProfile:
    Type: AWS::B2B::Profile
    Properties:
      BusinessContact:
        Name: "Default Business Contact"
        Email: "contact@example.com"
        Phone: "+1234567890"

  B2BITransformer:
    Type: AWS::B2B::Transformer
    Properties:
      MappingLogic: |
        {
          "EDI_X12_214": {
            "to": "JSON"
          }
        }
      InputFormat: "EDI"
      OutputFormat: "JSON"

  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-input"

  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-output"