AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: TagFilteredResourceGroup
      ResourceQuery:
        Type: TAG_FILTERS_1_0
        Query:
          ResourceTypeFilters:
            - AWS::EC2::Instance
            - AWS::RDS::DBInstance
            - AWS::SageMaker::NotebookInstance
            - AWS::SSM::Document
          TagFilters:
            - Key: Environment
              Values:
                - Production
                - Development
                - Testing