AWSTemplateFormatVersion: '2010-09-09'
Description: 'Production-ready DynamoDB table with one Local Secondary Index and one Global Secondary Index'

Parameters:
  TableName:
    Type: String
    Default: ExampleDynamoDB