AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2CloudWatchSSMIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2CloudWatchSSMIAMRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: EC2CloudWatchSSMIAMRole
      Roles:
        - !Ref EC2CloudWatchSSMIAMRole

Outputs:
  InstanceProfileName:
    Description: The name of the instance profile for EC2 instances
    Value: !GetAtt EC2InstanceProfile.InstanceProfileName
    Export:
      Name: EC2CloudWatchSSMInstanceProfile