AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create AWS Glue resources for crawling and cataloging CloudTrail logs stored in S3.

Resources:
  CloudTrailDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: cloudtrail_logs_db

  CloudTrailCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: cloudtrail-crawler
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: !Ref CloudTrailDatabase
      Targets:
        S3Targets:
          - Path: s3://kk-admin/cloud-trail/AWSLogs/
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE
      Configuration: |
        {
          "Version":1.0,
          "Grouping": {
            "TableGroupingPolicy": "CombineCompatibleSchemas"
          },
          "CrawlerOutput": {
            "Partitions": {
              "AddOrUpdateBehavior": "InheritFromTable"
            },
            "Tables": {
              "TablePrefix": "cloudtrail_"
            }
          }
        }

  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - arn:aws:s3:::kk-admin/cloud-trail/AWSLogs/*
                  - arn:aws:s3:::aws-glue-*/*
        - PolicyName: CloudWatchLogsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*