AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'my-s3-bucket-${AWS::AccountId}-${AWS::Region}'
      NotificationConfiguration:
        TopicConfigurations:
          - Event: 's3:ObjectCreated:*'
            Topic: !Ref SNSTopic

  SNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Sub 'my-s3-notification-topic-${AWS::AccountId}-${AWS::Region}'

  SNSTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      Topics:
        - !Ref SNSTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 's3.amazonaws.com'
            Action: 'SNS:Publish'
            Resource: !Ref SNSTopic
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:s3:::my-s3-bucket-${AWS::AccountId}-${AWS::Region}'

Outputs:
  S3BucketName:
    Description: 'Name of the S3 bucket'
    Value: !Ref S3Bucket

  SNSTopicARN:
    Description: 'ARN of the SNS topic'
    Value: !Ref SNSTopic