AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create a VPC and a private Amazon Route 53 Hosted Zone for internal DNS management.

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

  PrivateHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: example.com
      VPCs:
        - VPCId: !Ref MyVPC
          VPCRegion: !Ref "AWS::Region"
      HostedZoneConfig:
        Comment: Private hosted zone for internal DNS management

Outputs:
  HostedZoneId:
    Description: The ID of the created private hosted zone.
    Value: !Ref PrivateHostedZone