AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates an encrypted One Zone EFS file system in us-east-1a'

Resources:
  OneZoneFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      AvailabilityZoneName: us-east-1a
      BackupPolicy:
        Status: ENABLED
      FileSystemTags:
        - Key: Name
          Value: OneZoneEFS
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
      FileSystemPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "elasticfilesystem:*"
            Resource: !Sub "arn:aws:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:file-system/${AWS::StackName}-*"
      FileSystemType: ONE_ZONE_1

Outputs:
  FileSystemId:
    Description: ID of the created EFS file system
    Value: !Ref OneZoneFileSystem
  FileSystemArn:
    Description: ARN of the created EFS file system
    Value: !GetAtt OneZoneFileSystem.Arn