AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MainSecureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ReplicaBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDelivery

  AccessLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDelivery

  MainBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MainSecureBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !Sub 'arn:aws:s3:::${MainSecureBucket}'
              - !Sub 'arn:aws:s3:::${MainSecureBucket}/*'
            Condition:
              Bool:
                aws:SecureTransport: false