AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: redux-sample AppSync Query users

Parameters:
  ApiId:
    Type: String
  UserTableDataSourceName:
    Type: String

Resources:
  UsersQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Query
      FieldName: users
      DataSourceName: !Ref UserTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/scan-all.vm
      ResponseMappingTemplateS3Location: ../vtl/return-scan-result.vm