Resources:
  CustomerAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: The customer API for pet-clinic application
      Name: customer-api
      Tags:
        - Key: application
          Value: pet-clinic

  CustomerResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt
        - CustomerAPI
        - RootResourceId
      PathPart: customers
      RestApiId: !Ref CustomerAPI

  GETSingleCustomer:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CustomerAPI
      ResourceId: !Ref CustomerResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          "application/json": '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              "application/json": !Sub |
                '{ "statusCode": 200, "message": "Good, success!"}'
      MethodResponses:
        - StatusCode: 200

  # CustomerAPIProdDeployment:
  #   Type: AWS::ApiGateway::Deployment
  #   Properties:
  #     RestApiId: !Ref CustomerAPI
  #     StageName: prod