---
# Bashlinux::Kubernetes Master::EC2 Security group
#
#   Cloudformation template to deploy an EC2 security group
#   for the Kubernetes master nodes
#
#   Manuel F Martinez
#   Bashlinux
#   Los Angeles, CA
#
AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 Kubernetes Master Security Group template

###############################################################################
Parameters:

  Environment:
    Description: Kubernetes Cluster environment
    Type: String
    MinLength: "1"
    MaxLength: "20"
    Default: staging
    AllowedValues: [ "prod", "staging" ]
    ConstraintDescription: Environment name can only contain "prod" or "staging".

  Organization:
    Description: Organization or Customer name
    Type: String
    MinLength: "1"
    MaxLength: "32"
    Default: bashlinux
    AllowedPattern: "[a-zA-Z0-9\\-]*"
    ConstraintDescription: >
      Name of the organization must contains only letters, numbers and hyphens

###############################################################################
Resources:

  Ec2KubernetesMasterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access to the Kubernetes ports on the Control Plane
      VpcId: !ImportValue
          "Fn::Sub": "bashlinux-${Environment}-VpcId"
      Tags:
      - Key: Name
        Value: !Sub "${Organization}-${Environment}-kubernetes-master-sg"
      - Key: bashlinux:organization-name
        Value: !Ref Organization
      - Key: bashlinux:environment-name
        Value: !Ref Environment
      - Key: bashlinux:application-id
        Value: !Ref AWS::StackName
      - Key: bashlinux:can-delete
        Value: "false"
      - Key: !Sub "kubernetes.io/cluster/bashlinux-${Environment}"
        Value: "owned"

  ingressKubernetesFromMasterCalicoIPinIP:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Kubernetes: Calico IP-in-IP"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: 4

  ingressKubernetesDNS:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "DNS: Name resolution within for the cluster"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: udp
      FromPort: "53"
      ToPort: "53"

  ingressKubernetesCalicoBGP:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Kubernetes: Calico BGP"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "179"
      ToPort: "179"

  ingressKubernetesMetricsServerHTTPS:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Kubernetes: Metrics Server HTTPS"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "443"
      ToPort: "443"

  ingressKubernetesAPI:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Kubernetes: API server"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "6443"
      ToPort: "6443"

  ingressKubernetesEtcd:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Kubernetes: Kube API server and ETCD"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "2379"
      ToPort: "2380"

  ingressKubernetesKubelet:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Kubernetes: Kubelet API"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "10250"
      ToPort: "10250"

  ingressKubernetesKubeProxy:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Kubernetes: Kube-proxy health"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "10256"
      ToPort: "10256"

  ingressKubernetesScheduler:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Kubernetes: kube-scheduler"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "10259"
      ToPort: "10259"

  ingressKubernetesController:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Kubernetes: kube-controller-manager"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "10257"
      ToPort: "10257"

  egressKubernetesCalicoIPinIP:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: "Kubernetes: Calico IP-in-IP"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      DestinationSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: 4

  egressKubernetesDNS:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: "DNS: Name resolution within for the cluster"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      DestinationSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: udp
      FromPort: "53"
      ToPort: "53"

  egressKubernetesCalicoBGP:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: "Kubernetes: Calico BGP"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      DestinationSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "179"
      ToPort: "179"

  egressKubernetesAnywhereHTTPS:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: "Kubernetes: Access anywhere via HTTPS"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      CidrIp: "0.0.0.0/0"
      IpProtocol: tcp
      FromPort: "443"
      ToPort: "443"

  egressKubernetesAPI:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: "Kubernetes: API server"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      DestinationSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "6443"
      ToPort: "6443"

  egressKubernetesEtcd:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: "Kubernetes: Kube API server and ETCD"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      DestinationSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "2379"
      ToPort: "2380"

  egressKubernetesKubelet:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: "Kubernetes: Kubelet API"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      DestinationSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "10250"
      ToPort: "10250"

  egressKubernetesKubeProxy:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: "Kubernetes: Kube-proxy health"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      DestinationSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "10256"
      ToPort: "10256"

  egressKubernetesScheduler:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: "Kubernetes: kube-scheduler"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      DestinationSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "10259"
      ToPort: "10259"

  egressKubernetesController:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: "Kubernetes: kube-controller-manager"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      DestinationSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "10257"
      ToPort: "10257"

  # Kubelet API from the Master Security Group --------------------------------
  ingressKubernetesAPIFromBastion:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Kubernetes: API server"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !ImportValue
        "Fn::Sub": "bashlinux-${Environment}-Ec2BastionSecurityGroupId"
      IpProtocol: tcp
      FromPort: "6443"
      ToPort: "6443"

  ingressKubernetesSSHFromBastion:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "SSH: Remote administration"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !ImportValue
        "Fn::Sub": "bashlinux-${Environment}-Ec2BastionSecurityGroupId"
      IpProtocol: tcp
      FromPort: "22"
      ToPort: "22"

  ingressKubernetesZabbixFromBastion:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Zabbix: Passive agent incoming"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !ImportValue
        "Fn::Sub": "bashlinux-${Environment}-Ec2BastionSecurityGroupId"
      IpProtocol: tcp
      FromPort: "10050"
      ToPort: "10050"

  ingressKubernetesFromBastion:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Kubernetes: Kubelete API"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      SourceSecurityGroupId: !ImportValue
        "Fn::Sub": "bashlinux-${Environment}-Ec2BastionSecurityGroupId"
      IpProtocol: tcp
      FromPort: "10250"
      ToPort: "10250"

  egressKubernetesZabbixToBastion:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: "Zabbix: Active agent outgoing"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      DestinationSecurityGroupId: !ImportValue
        "Fn::Sub": "bashlinux-${Environment}-Ec2BastionSecurityGroupId"
      IpProtocol: tcp
      FromPort: "10051"
      ToPort: "10051"

  egressKubernetesFromBastion:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: "Kubernetes: API server"
      GroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      DestinationSecurityGroupId: !ImportValue
        "Fn::Sub": "bashlinux-${Environment}-Ec2BastionSecurityGroupId"
      IpProtocol: tcp
      FromPort: "6443"
      ToPort: "6443"

  egressKubernetesFromBastion:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: "Kubernetes: Kubelete API"
      GroupId: !ImportValue
        "Fn::Sub": "bashlinux-${Environment}-Ec2BastionSecurityGroupId"
      DestinationSecurityGroupId: !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: "10250"
      ToPort: "10250"

###############################################################################
Outputs:

  Ec2KubernetesMasterSecurityGroupId:
    Description: The Security Group ID to use for Kubernetes Master nodes
    Value:  !GetAtt Ec2KubernetesMasterSecurityGroup.GroupId
    Export:
      Name: !Sub "${Organization}-${Environment}-master-Ec2KubernetesSecurityGroupId"