---
# Bashlinux::Private::Route53::Hosted Zone
#
#   Cloudformation template to deploy private hosted zone
#
#   Manuel F Martinez
#   Bashlinux
#   Los Angeles, CA
#
AWSTemplateFormatVersion: "2010-09-09"
Description: Route53 Private Hosted Zone template

###############################################################################
Parameters:

  Environment:
    Description: Working environment
    Type: String
    MinLength: "1"
    MaxLength: "20"
    Default: staging
    AllowedValues: [ "prod", "staging" ]
    ConstraintDescription: >
      Environment name can only contain "prod" or "staging"

###############################################################################
Mappings:

  Env2Domains:
    prod:
      Domain: prod.bashlinux.com
    staging:
      Domain: staging.bashlinux.com

###############################################################################
Resources:

  EnvPrivateHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Sub "Domain in: ${Environment}"
      Name: !FindInMap [ Env2Domains, !Ref Environment, Domain ]
      VPCs:
      - VPCId: !ImportValue
          "Fn::Sub": "bashlinux-${Environment}-VpcId"
        VPCRegion: !Ref AWS::Region
      HostedZoneTags:
      - Key: Name
        Value: !FindInMap [ Env2Domains, !Ref Environment, Domain ]
      - Key: bashlinux:environment-name
        Value: !Ref Environment
      - Key: bashlinux:application-id
        Value: !Ref AWS::StackName
      - Key: bashlinux:can-delete
        Value: "false"
      - Key: bashlinux:network-visibility
        Value: private

###############################################################################
Outputs:

  EnvPrivateHostedZoneId:
    Description: "Route53: Hosted Zone ID"
    Value: !Ref EnvPrivateHostedZone
    Export:
      Name: !Sub "bashlinux-${Environment}-PrivateHostedZoneId"

  EnvPrivateDomain:
    Description: "DNS: Actual domain name"
    Value: !FindInMap [ Env2Domains, !Ref Environment, Domain ]
    Export:
      Name: !Sub "bashlinux-${Environment}-EnvPrivateDomain"