AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon Aurora MySQL cluster with two instances and custom parameter group

Parameters:
  DBClusterName:
    Type: String
    Description: The name of the database cluster
  DBInstance