AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EFSVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: EFS-Test-VPC

  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EFS Mount Target Security Group
      VpcId: !Ref EFSVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          CidrIp: !GetAtt EFSVPC.CidrBlock
      Tags:
        - Key: Name
          Value: EFS-Test-SG

  EFSSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref EFSVPC
      AvailabilityZone: us-east-1a
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: EFS-Test-Subnet

  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
      Encrypted: true
      Tags:
        - Key: Name
          Value: Test-EFS-Filesystem

  EFSMountTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Ref EFSSubnet
      SecurityGroups:
        - !Ref EFSSecurityGroup

Outputs:
  FileSystemId:
    Description: EFS File System ID
    Value: !Ref EFSFileSystem
  FileSystemDNS:
    Description: EFS DNS Name
    Value: !GetAtt EFSFileSystem.DNSName
  SecurityGroupId:
    Description: EFS Security Group ID
    Value: !Ref EFSSecurityGroup
  SubnetId:
    Description: EFS Mount Target Subnet
    Value: !Ref EFSSubnet