AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LabBucketName:
    Type: String
Resources:
  Lab111:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join [ "-", [ !Ref 'AWS::AccountId', !Ref 'LabBucketName' ] ]