AWSTemplateFormatVersion: 2010-09-09
Description: "Template used to build AWS Data Lake infrastructure"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "pylake-bucket"
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "888888888888"
      DatabaseInput:
        Name: !Sub "pylake_db"