AWSTemplateFormatVersion: "2010-09-09"
Description: A service lambda function to perform operations on buckets

Resources:
  PewServiceLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: ServiceLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                  - s3:ListBucket
                  - s3:DeleteBucket
                Resource:
                  - !Sub "arn:aws:s3:::pew-marketdata-${AWS::AccountId}"
                  - !Sub "arn:aws:s3:::pew-report-${AWS::AccountId}"
                  - !Sub "arn:aws:s3:::pew-resources-${AWS::AccountId}"
                  - !Sub "arn:aws:s3:::pew-website-${AWS::AccountId}"
                  - !Sub "arn:aws:s3:::pew-marketdata-${AWS::AccountId}/*"
                  - !Sub "arn:aws:s3:::pew-report-${AWS::AccountId}/*"
                  - !Sub "arn:aws:s3:::pew-resources-${AWS::AccountId}/*"
                  - !Sub "arn:aws:s3:::pew-website-${AWS::AccountId}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

  PewServiceLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Pew-Service
      Runtime: python3.11
      MemorySize: 512
      Timeout: 150
      TracingConfig:
        Mode: "PassThrough"
      Handler: pew_service_lambda.lambda_handler
      Role: !GetAtt PewServiceLambdaRole.Arn
      Code:
        S3Bucket: !Sub "pew-resources-${AWS::AccountId}"
        S3Key: pew_service_lambda.zip