AWSTemplateFormatVersion: '2010-09-09'
Description: Network Load Balancer with EIPs in 2 AZs
Resources:
  NLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyNLB
      Scheme: internet-facing
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      Type: network
      IpAddressType: ipv4
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NLB
      Port: 80
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: MyTargetGroup
      Port: 80
      Protocol: TCP
      VpcId: !Ref VPC
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
  EIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  EIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  EIPAssociation1:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt EIP1.AllocationId
      NetworkInterfaceId: !GetAtt NLB.NetworkInterfaces.0
  EIPAssociation2:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt EIP2.AllocationId
      NetworkInterfaceId: !GetAtt NLB.NetworkInterfaces.1
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  Subnet1:
    Type: String
    Description: Subnet ID in AZ1
  Subnet2:
    Type: String
    Description: Subnet ID in AZ2

Outputs:
  NLBArn:
    Value: !Ref NLB
    Description: The ARN of the Network Load Balancer
  NLBDNSName:
    Value: !GetAtt NLB.DNSName
    Description: The DNS name of the Network Load Balancer

