AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a standard SQS queue.
Resources:
  MySQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyStandardQueue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 86400
      DelaySeconds: 0
      ReceiveMessageWaitTimeSeconds: 0
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDeadLetterQueue.Arn
        maxReceiveCount: 3
  MyDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyDeadLetterQueue
Outputs:
  QueueURL:
    Value: !GetAtt MySQSQueue.QueueUrl
    Description: URL of the SQS Queue
  QueueArn:
    Value: !GetAtt MySQSQueue.Arn
    Description: ARN of the SQS Queue
  DeadLetterQueueURL:
    Value: !GetAtt MyDeadLetterQueue.QueueUrl
    Description: URL of the Dead Letter Queue
  DeadLetterQueueArn:
    Value: !GetAtt MyDeadLetterQueue.Arn
    Description: ARN of the Dead Letter Queue

