

AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a default Amazon S3 bucket.
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: MyDefaultS3Bucket
Outputs:
  BucketName:
    Value: !Ref MyS3Bucket
    Description: Name of the S3 bucket
  BucketArn:
    Value: !GetAtt MyS3Bucket.Arn
    Description: ARN of the S3 bucket

