AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template for creating an Amazon S3 bucket configured for website hosting with a DeletionPolicy set to Retain.
Parameters:
  BucketName:
    Description: "The name of the S3 bucket for website hosting. Must be globally unique."
    Type: String
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WebsiteBucket
                - '/*'
Outputs:
  WebsiteURL:
    Description: "URL for website hosted on S3"
    Value: !GetAtt WebsiteBucket.WebsiteURL