AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an IAM user for OpsBerryAI with read-only access to CloudTrail and IAM.

Resources:

  OpsBerryAIUser:
    Type: AWS::IAM::User
    Properties:
      UserName: OpsBerryAI

  OpsBerryAIReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: OpsBerryAIReadOnlyPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "cloudtrail:DescribeTrails"
              - "cloudtrail:GetTrailStatus"
              - "cloudtrail:ListTrails"
              - "cloudtrail:LookupEvents"
              - "iam:ListUsers"
              - "iam:GetUser"
              - "iam:ListRoles"
              - "iam:GetRole"
            Resource: "*"
      Users:
        - !Ref OpsBerryAIUser

  OpsBerryAIUserAccessKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref OpsBerryAIUser

Outputs:
  AccessKeyId:
    Description: "Access Key ID for OpsBerryAI"
    Value: !Ref OpsBerryAIUserAccessKeys
    Export:
      Name: OpsBerryAIUserAccessKeyId

  SecretAccessKey:
    Description: "Secret Access Key for OpsBerryAI"
    Value: !GetAtt OpsBerryAIUserAccessKeys.SecretAccessKey
    Export:
      Name: OpsBerryAIUserSecretAccessKey