AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template to enable GuardDuty detector for security monitoring'

Parameters:
  FindingPublishingFrequency:
    Type: String
    Default: FIFTEEN_MINUTES
    AllowedValues:
      - FIFTEEN_MINUTES
      - ONE_HOUR
      - SIX_HOURS
    Description: 'Frequency for publishing updated findings'
  
  EnableGuardDuty:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: 'Enable or disable GuardDuty detector'

Resources:
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: !Ref EnableGuardDuty
      FindingPublishingFrequency: !Ref FindingPublishingFrequency

Outputs:
  DetectorId:
    Description: 'The ID of the GuardDuty detector'
    Value: !Ref GuardDutyDetector