AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync Mutation deleteSessionData

Parameters:
  ApiId:
    Type: String
  SessionDataTableDataSourceName:
    Type: String

Resources:
  DeleteSessionDataMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: deleteSessionData
      DataSourceName: !Ref SessionDataTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/delete-item-where-id-input-id.vm
      ResponseMappingTemplateS3Location: ../vtl/return-result.vm