AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: EnrichmentQueue

  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/events/enrichment-logs
      RetentionInDays: 14

  EventBridgePipeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EventBridgePipePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt SQSQueue.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/events/enrichment-logs:*
              - Effect: Allow
                Action:
                  - execute-api:Invoke
                Resource: arn:aws:execute-api:*:*:*/GET/us/*

  EventBridgePipe:
    Type: AWS::Events::Pipe
    Properties:
      RoleArn: !GetAtt EventBridgePipeRole.Arn
      Source:
        Arn: !GetAtt SQSQueue.Arn
        Parameters:
          BatchSize: 10
          MaximumBatchingWindowInSeconds: 60
      Enrichment:
        HttpParameters:
          PathParameterValues:
            - $.body.zipCode
        HttpMethod: GET
        Endpoint: https://api.zippopotam.us
      Target:
        Arn: !GetAtt CloudWatchLogGroup.Arn
        Parameters:
          InputTemplate: '{"zipCode": <$.body.zipCode>, "location": <$.enrichedData>}'
Outputs:
  SQSQueueURL:
    Description: URL of the SQS Queue
    Value: !Ref SQSQueue

  CloudWatchLogGroupName:
    Description: Name of the CloudWatch Log Group
    Value: !Ref CloudWatchLogGroup

  EventBridgePipeARN:
    Description: ARN of the EventBridge Pipe
    Value: !GetAtt EventBridgePipe.Arn