AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS CloudFormation Template to create an SNS Topic with an email subscription.

Parameters:
  EmailAddress:
    Description: The email address to receive SNS notifications.
    Type: String
    Default: test@test.com

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: EmailNotificationTopic

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref EmailAddress
      TopicArn: !Ref SNSTopic

Outputs:
  SNSTopicARN:
    Description: The ARN of the SNS Topic
    Value: !Ref SNSTopic