AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create an IAM role with AWS managed policies and an instance profile for EC2 instances to integrate with Amazon CloudWatch and AWS Systems Manager.

Resources:
  EC2IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Path: /

  EC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - Ref: EC2IAMRole
      Path: /

Outputs:
  IAMRoleName:
    Description: The name of the IAM Role for EC2 instances.
    Value: !Ref EC2IAMRole

  InstanceProfileName:
    Description: The name of the Instance Profile for EC2 instances.
    Value: !Ref EC2InstanceProfile