AWSTemplateFormatVersion: 2010-09-09

Parameters:
  mainStackName:
    Type: String
    Default: turkey-pg-1
  DBInstanceClass:
    Type: String
  DBAllocatedStorage:
    Type: Number
  PGpwd:
    Type: String
  PrivateSubnet1Id:
    Type: String
  PrivateSubnet2Id:
    Type: String
  DbGroupId:
    Type: String

Resources:
  SubnetGrp:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: turkey data
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id

  PG:
    DependsOn: SubnetGrp
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Ref mainStackName
      DBName: turkey
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: postgres
      EngineVersion: 13.4
      MasterUsername: postgres
      MasterUserPassword: !Ref PGpwd
      DBSubnetGroupName: !Ref SubnetGrp
      # MonitoringInterval: '60'
      # MonitoringRoleArn: 'arn:aws:iam::123456789012:role/rds-monitoring-role'
      VPCSecurityGroups:
        - !Ref DbGroupId

Outputs:
  dbHost:
    Value: !GetAtt PG.Endpoint.Address