AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for EC2 instances with read-only access to IAM metadata

Resources:
  EC2IAMReadOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2IAMReadOnlyRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess

Outputs:
  EC2IAMReadOnlyRoleArn:
    Description: The ARN of the EC2 IAM Read-Only Role
    Value: !GetAtt EC2IAMReadOnlyRole.Arn
    Export:
      Name: EC2IAMReadOnlyRoleArn